GateLog/ViewModels/EditViewModel.cs
using GateLog.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GateLog.ViewModels
{
    public class EditViewModel : ViewModel
    {
        public int Id { get; set; }
        public List<Truck> Trucks = new List<Truck>();
        public string Trip { get; set; }
        public string Shipper { get; set; }
        [Required]
        public string Tractor { get; set; }
        [Required]
        public string Carrier { get; set; }
        public string Trailer { get; set; }
        public override string Seal { get; set; }
        [Required]
        public InOutEnum InOrOut { get; set; }
        public CompanyEnum Company { get; set; }
        public override bool IsEmpty { get; set; }
        public  bool RedirectedBecauseOfBadTrip { get; set; }
        public  bool RedirectedBecauseOfBadDoor { get; set; }
        public  bool RedirectedBecauseOfBadDate { get; set; }
        [MaxLength(3)]
        public override string Door { get; set; }
        public override bool InYard { get; set; }
        public override bool OnFence { get; set; }
        public override bool IsRelay { get; set; }
        public override bool InDropLot { get; set; }
        public new DateTime DateAndTime { get; set; }

        public string[] GetTrips()
        {
            string[] trips = Trip.Split(",");
            for (int i = 0; i < trips.Length; i++)
            {
                trips[i] = trips[i].Trim();
            }
            return trips;
        }

        public bool HasTrip(string trip)
        {
            if (Trip == null)
            {
                return false;
            }

            trip = trip.Trim();
            foreach (string s in GetTrips())
            {
                if (s.Trim().Equals(trip))
                {
                    return true;
                }
            }
            return false;
        }



    }
}

GateLog/Controllers/EditController.cs
using GateLog.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GateLog.Models;
using GateLog.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace GateLog.Controllers 
{
    [Authorize]
    public class EditController : Controller
    {
        IDataServices dataServices;
        IDateTimeService dateTimeServices;
        public EditController(IDataServices dataServices, IDateTimeService dateTimeServices)
        {
            this.dataServices = dataServices;
            this.dateTimeServices = dateTimeServices;
        }

        [HttpGet]
        public IActionResult EditTruck(int id)
        {
            Truck truck = dataServices.GetById(id);
            EditViewModel model = new EditViewModel();

            model.Carrier = truck.Carrier;
            model.DateAndTime = truck.DateAndTime;
            model.Door = truck.Door;
            model.Id = truck.Id;
            model.Seal = truck.Seal;
            model.Door = truck.Door;
            model.Tractor = truck.Tractor;
            model.Trailer = truck.Trailer;
            model.Trip = truck.Trip;
            model.InYard = truck.InYard;
            model.IsEmpty = truck.IsEmpty;
            model.IsRelay = truck.IsRelay; 
            model.InDropLot = truck.InDropLot;
            model.OnFence = truck.OnFence;
            model.InOrOut = truck.InOrOut;
            model.Company = truck.Company;
            model.Shipper = truck.Shipper;


            return View(model);

        }

        [HttpPost]
        public IActionResult EditTruck(EditViewModel editModel)
        {

            editModel.RedirectedBecauseOfBadTrip = false;
            editModel.RedirectedBecauseOfBadDoor = false;
            editModel.RedirectedBecauseOfBadDate = false;

            if (!ModelState.IsValid)
            {
                editModel.Trucks = dataServices.GetLastNTrucksFromList(20, dataServices.GetAllTrucks());
                return View(editModel);
            }
            Truck model = dataServices.GetById(editModel.Id);

            if ((editModel.Trip != null && dataServices.AreValidTrips(editModel.GetTrips()))
                || editModel.Trip == null)
            {
                model.Trip = editModel.Trip;
            }

            else
            {
                editModel.RedirectedBecauseOfBadTrip = true;
                editModel.Trucks = dataServices.GetLastNTrucksFromList(20, dataServices.GetAllTrucks());
                return View(editModel);
            }


            if (!dataServices.FilterDoor(editModel))
            {
                editModel.RedirectedBecauseOfBadDoor = true;
                editModel.Trucks = dataServices.GetLastNTrucksFromList(20, dataServices.GetAllTrucks());
                return View(editModel);
            }

            if(!dateTimeServices.ConvertDateTime(editModel, model))
            {
                editModel.RedirectedBecauseOfBadDate = true;
                editModel.Trucks = dataServices.GetLastNTrucksFromList(20, dataServices.GetAllTrucks());
                return View(editModel);
            }

            dataServices.FilterSeal(editModel);

            if(model.LogId != null)
            {
                if(editModel.Trailer == null)
                {
                    model.LogId = null; 
                }
                else if(model.Trailer != editModel.Trailer)
                {
                    model.LogId = null;
                }
            }
            if(model.Trailer != null && editModel.Trailer == null)
            {
                editModel.InDropLot = false;
                editModel.InYard = false;
                editModel.IsRelay = false;
                editModel.OnFence = false;
                editModel.IsEmpty = false;
                editModel.Door = null;

                
            }
            


            model.Carrier = editModel.Carrier;
            model.Shipper = editModel.Shipper;
            model.Tractor = editModel.Tractor;
            model.InOrOut = editModel.InOrOut;
            model.Seal = editModel.Seal;
            model.IsEmpty = editModel.IsEmpty;
            model.InDropLot = editModel.InDropLot;
            model.IsRelay = editModel.IsRelay;
            model.InYard = editModel.InYard;
            model.OnFence = editModel.OnFence;
            model.Trailer = editModel.Trailer;
            model.Door = editModel.Door;
            model.Id = editModel.Id;
            model.Company = editModel.Company;
            dataServices.UpdateTruck(model);

            if (dataServices.GetInTrailer(model.Id) != null)
            {
                if (editModel.Trailer == null || editModel.InOrOut == InOutEnum.Out)
                {
                    dataServices.RemoveInTrailer(editModel.Id);
                }
            }
            else
            {
                if (editModel.Trailer != null && editModel.InOrOut == InOutEnum.In)
                {
                    dataServices.AddInTrailer(model);
                }
            }

            return RedirectToAction("HistoryPage", "History");


        }

        public IActionResult RemoveTruck(int id)
        {
            dataServices.RemoveTruck(id);
            if(dataServices.GetInTractor(id) != null)
            {
                dataServices.RemoveInTractorFromEntryId(id);
            }
            if(dataServices.GetInTrailer(id) != null)
            {
                dataServices.RemoveInTrailerFromEntryId(id);
            }
            return RedirectToAction("Index", "Home");
        }

    }
}

GateLog/Views/Edit/EditTruck.cshtml
@{
    ViewBag.Title = "Edit Truck";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model GateLog.ViewModels.EditViewModel
@using GateLog.Models

@section script{

}
@section header{
    Edit Truck
}

<script type="text/javascript">
    var cont = document.getElementById("cont");
    cont.classList.remove("container");
    cont.style.marginTop = "10%";
</script>

<form method="post">
    <table class="table table-bordered table-primary table-sm table-responsive">
        <thead>
            <tr>
                <th>Month</th>
                <th>Day</th>
                <th>Year</th>
                <th>Hour</th>
                <th>Minute</th>
                <th>Carrier</th>
                <th>Tractor</th>
                <th>Trailer</th>
                <th>Trip</th>
                <th>Seal/Empty</th>
                <th>Shipper</th>
                <th>In/Out</th>
                <th>Door</th>
                <th>Company</th>
                <th>Submit/Edit</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <td><input size="2" asp-for="Month" value="@Model.DateAndTime.Month" /></td>
                <td><input size="2" asp-for="Day" value="@Model.DateAndTime.Day" /></td>
                <td><input size="4" asp-for="Year" value="@Model.DateAndTime.Year" /></td>
                <td><input size="2" asp-for="Hour" value="@Model.DateAndTime.TimeOfDay.ToString().Substring(0, 2)" /></td>
                <td><input size="2" asp-for="Minute" value="@Model.DateAndTime.TimeOfDay.ToString().Substring(3, 2)" /></td>
                <td><input size="10" asp-for="Carrier" /></td>
                <td><input size="10" asp-for="Tractor" /></td>
                <td><input size="10" asp-for="Trailer" /></td>
                <td><input asp-for="Trip" /></td>

                @if (@Model.IsEmpty == true)
                {
                    <td><input asp-for="Seal" value="Empty" /></td>

                }
                @if (@Model.InDropLot == true)
                {

                    <td><input asp-for="Seal" value="Drop Lot" /></td>

                }

                @if (@Model.IsRelay == true)
                {
                    <td><input asp-for="Seal" value="Relay" /></td>

                }

                @if (@Model.InDropLot == false && @Model.IsRelay == false && @Model.IsEmpty == false)
                {
                    <td><input asp-for="Seal" /></td>

                }

                <td><input asp-for="Shipper" /></td>

                <td><select asp-for="InOrOut" asp-items="@Html.GetEnumSelectList<GateLog.Models.InOutEnum>()"></select></td>

                @if (@Model.InYard == true)
                {
                    <td><input size="3" asp-for="Door" value="Y" /></td>

                }

                @if (@Model.OnFence == true)
                {
                    <td><input size="3" asp-for="Door" value="F" /></td>

                }

                @if (@Model.OnFence == false && @Model.InYard == false)
                {
                    <td><input size="3" asp-for="Door" /></td>
                }

                <td>
                    <select asp-for="Company" asp-items="@Html.GetEnumSelectList<GateLog.Models.CompanyEnum>()"></select>
                </td>

                <td><input type="submit" class="btn btn-sm btn-primary text-white" name="update" value="Update" /></td>
            </tr>
            <tr><td style="margin-bottom: 10%"></td></tr>
        </tbody>

    </table>
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="DateAndTime" />

    <div style="color:red" asp-validation-summary="All">
        @if (@Model.RedirectedBecauseOfBadTrip == true)
        {
            <p>*Invalid Trip</p>

        }
        @if (@Model.RedirectedBecauseOfBadDoor == true)
        {
            <p>*Invalid Door</p>

        }
        @if (@Model.RedirectedBecauseOfBadDate == true)
        {
            <p>*Invalid Date Or Time</p>

        }
    </div>
</form>

<div style="margin-left: 30%" class="text-white">
    <ul>
        <li>Make sure to entr f or F for Fence and y or Y for Yard.</li>
        <li>Do not enter Fence or Yard.</li>
    </ul>
</div>


<div style="text-align: center"><a class="btn btn-light" asp-action="RemoveTruck" asp-controller="Edit" asp-route-id="@Model.Id">Remove This Truck From History</a></div>