GateLog/Controllers/LogController.cs
using GateLog.Models;
using GateLog.Services;
using GateLog.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GateLog.Controllers
{
    [Authorize]
    public class LogController : Controller
    {
        IDataServices dataServices; 
        public LogController(IDataServices dataServices)
        {
            this.dataServices = dataServices; 
        }

        public IActionResult LogPage()
        {
            LogViewModel viewModel = new LogViewModel();
            viewModel.LogEntries = dataServices.GetAllLogEntries();
            if(viewModel.LogEntries.Count > 500)
            {
                viewModel.LogEntries = viewModel.LogEntries.GetRange(0, 500);
            }
            return View(viewModel);
        }

        public IActionResult SpecificLog(int id)
        {
            LogEntry log = dataServices.GetAllLogEntries().FirstOrDefault(r => r.Id == id);
            return View(log);
        }
    }
}

GateLog/Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <style>
        table, tr, th, td {
            border: solid;
            border-width: 1px;
            border-color: black;
        }
    </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    @*<link rel="stylesheet" href="~/node_modules/bootstrap/dist/css/bootstrap.css" />
        <script type="text/javascript" src="~/node_modules/jquery/dist/jquery.js"></script>
        <script type="text/javascript" src="~/node_modules/popper.js/dist/umd/popper.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>*@

</head>
<body>

    @*<div style="text-align: center; margin-bottom: 2%" class="display-1"><span class="badge bg-primary badge-pill text-white">Gate Log</span></div>*@

    @*<div style="background-color: maroon; border-top: inset; border-top-color: silver;
                    border-top-width: 3px; border-bottom: inset; border-bottom-color: silver;
                    border-bottom-width: 3px; width: 100%; height: 15%">

            <p style="margin-left: 44%; font-size: 3em">
                @RenderSection("header", required: true)
            </p>
        </div>*@
    <nav class=" sticky-top navbar bg-primary">
        <table style="border:none">
            <tr style="border:none">
                <td style="border:none">
                    <div class="btn-group">
                        <a style="font-size: 2em" class="btn btn-primary text-white;" id="Home1" asp-action="Index" asp-controller="Home">Home</a>
                        <a style="font-size: 2em" class="btn btn-primary text-white" id="Search1" asp-action="SearchPage" asp-controller="Search">Search</a>
                        <a style="font-size: 2em" class="btn btn-primary text-white" id="History1" asp-action="HistoryPage" asp-controller="History" asp-route-i="0">History</a>
                        <div class="dropdown">
                            <button style="font-size: 2em" class="btn btn-primary dropdown-toggle" id="Carriers1" data-toggle="dropdown">Carriers</button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-action="AllCarriers" asp-controller="Carrier">All Carriers</a>
                                <a class="dropdown-item" asp-action="AddCarrier" asp-controller="Carrier">Add Carrier</a>
                            </div>
                        </div>
                        <a style="font-size: 2em" class="btn btn-primary text-white" id="Tractors1" asp-action="TractorsInLot" asp-controller="InLot">Tractors In Lot</a>
                        <a style="font-size: 2em" class="btn btn-primary text-white" id="Trailers1" asp-action="TrailersInLot" asp-controller="InLot">Trailers In Lot</a>
                        <a style="font-size: 2em" class="btn btn-primary text-white" id="Log1" asp-action="LogPage" asp-controller="Log">Log</a>
                    </div>
                </td>
                @if (User.Identity.Name.Equals("TestAdmin2018"))
                {
                    <td class="bg-primary" style="border:none">
                        <div>
                            <a style="font-size: 2em" class="btn btn-primary text-white" id="TracTrail" asp-action="Add" asp-controller="TracTrail">Add Trac/Trail</a>
                        </div>
                    </td>
                }
                <td class="bg-primary" style="border:none">
                    <div>
                        <a style="font-size: 2em" class="btn btn-primary text-white" id="Logout" asp-action="Logout" asp-controller="Account"><strong>Sign Out</strong></a>
                    </div>
                </td>
            </tr>
        </table>

    </nav>
    <header style="text-align: center; margin-top: 5%; margin-bottom: 5%" class="container display-3">
        <span class="text-primary">
            @RenderSection("header", required: false)
        </span>
    </header>
    @*<div style="background-color: antiquewhite; margin-left: 10%; margin-top: .2%; width: 80%">
        <div style="margin-left: 15%; margin-top: 10%">*@

    <div id="cont" class="container bg-primary" style="padding: 1%">
        @RenderBody()
    </div>
    @*</div>
        </div>*@
    <div style="margin-top: 2%; text-align: center">
        @RenderSection("footer", required: false)
    </div>

    <nav class="navbar bg-light" style="display: none">
        <div class="container-fluid">
            <a class="btn btn-light" id="Home2" asp-action="Index" asp-controller="Home">Home</a>&nbsp;&nbsp;
            <a class="btn btn-light" id="Search2" asp-action="SearchPage" asp-controller="Search">Search</a>&nbsp;&nbsp;
            <a class="btn btn-light" id="History2" asp-action="HistoryPage" asp-controller="History" asp-route-i="0">History</a>&nbsp;&nbsp;
            <button class="btn btn-light dropdown-toggle" data-toggle="dropdown">Carriers</button>
            <div class="dropdown-menu">
                <a class="btn btn-light" id="Carriers2" asp-action="AllCarriers" asp-controller="Carrier">Carriers</a>&nbsp;&nbsp;
            </div>

            <a class="btn btn-light" id="Tractors2" asp-action="TractorsInLot" asp-controller="InLot">Tractors In Lot</a>&nbsp;&nbsp;
            <a class="btn btn-light" id="Trailers2" asp-action="TrailersInLot" asp-controller="InLot">Trailers In Lot</a>&nbsp;&nbsp;
            <a class="btn btn-light" id="Log2" asp-action="LogPage" asp-controller="Log">Log</a>
        </div>
    </nav>
    @RenderSection("script", required: true)

</body>
</html>